version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ..
            dockerfile: ./docker/Dockerfile
        image: rss-parser
        container_name: rss-parser-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../src:/var/www
        networks:
            - rss-parser
        depends_on:
            - db
            - nginx
    db:
        image: mysql:8.0
        platform: linux/x86_64
        container_name: rss-parser-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: rss-parser
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ../docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - rss-parser
    nginx:
        image: nginx:1.17-alpine
        container_name: rss-parser-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ../src:/var/www
            - ../docker/nginx:/etc/nginx/conf.d
        networks:
            - rss-parser
networks:
    rss-parser:
        driver: bridge
