version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ..
            dockerfile: docker/Dockerfile
        image: test-task
        container_name: test-task-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ../src:/var/www
        networks:
            - test-task
        depends_on:
            - db
            - nginx
    db:
        image: mysql:8.0
        container_name: test-task-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test-task
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ../docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - test-task
    nginx:
        image: nginx:1.17-alpine
        container_name: test-task-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ../src:/var/www
            - ../docker/nginx:/etc/nginx/conf.d
        networks:
            - test-task
networks:
    test-task:
        driver: bridge
